*********************************************************/

BLOCK: XO_2_0
**MILKYWAY_DATABASE: ./INVX8.icv.lvs/XTROUT
TCAD_GRD_FILE: ./starrc/max/saed32nm_1p9m_Cmax.nxtgrd
**MAPPING_FILE: ./pex_grd_map.nominal
ICV_RUNSET_REPORT_FILE: ./pex_runset_report

COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
EXTRACTION: RC
MILKYWAY_EXTRACT_VIEW: YES
CASE_SENSITIVE: NO
NETLIST_FORMAT: SPF
NETLIST_NODE_SECTION: YES
NETLIST_CONNECT_SECTION: YES
NETLIST_SUBCKT: YES
NETLIST_PASSIVE_PARAMS: YES
NETLIST_TAIL_COMMENTS: YES
NETLIST_DELIMITER: :
REDUCTION: NO
XREF: YES
EXTRACT_VIA_CAPS: NO
IGNORE_CAPACITANCE: NONE
KEEP_VIA_NODES: NO
MAGNIFY_DEVICE_PARAMS:NO
METAL_FILL_POLYGON_HANDLING: IGNORE
MOS_GATE_DELTA_RESISTANCE: NO
REMOVE_DANGLING_NETS: NO
REMOVE_FLOATING_NETS: NO
TRANSLATE_RETAIN_BULK_LAYERS: YES
SKIP_CELLS: !*
HIERARCHICAL_SEPARATOR: |
*OBSERVATION_POINTS: *
EXTRA_GEOMETRY_INFO: NODE

HN_NETLIST_SPICE_TYPE: n105 X
HN_NETLIST_SPICE_TYPE: p105 X
HN_NETLIST_SPICE_TYPE: n105_lvt X
HN_NETLIST_SPICE_TYPE: p105_lvt X
HN_NETLIST_SPICE_TYPE: n105_hvt X
HN_NETLIST_SPICE_TYPE: p105_hvt X
HN_NETLIST_SPICE_TYPE: n18 X
HN_NETLIST_SPICE_TYPE: p18 X
HN_NETLIST_SPICE_TYPE: n25 X
HN_NETLIST_SPICE_TYPE: p25 X

OA_LIB_NAME:
OA_VIEW_NAME: starrc
OA_MARKER_SIZE: 0.1
OA_REMOVE_SPICECARD_PREFIX: NO
OA_DEVICE_MAPPING_FILE: ../starrc/saed32nm_1p9m_device.map
