*********************************************************/

BLOCK: testcell 
MILKYWAY_DATABASE: ../testcell.hercules.lvs/TOPCELLNAME_MILKYWAY
TCAD_GRD_FILE: ./starrc/min/saed32nm_1p9m_Cmin.nxtgrd
MAPPING_FILE: ./starrc/saed32nm_1p9m_layer.map

COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
EXTRACTION: RC
MILKYWAY_EXTRACT_VIEW: YES
CASE_SENSITIVE: NO
NETLIST_FORMAT: OA
NETLIST_NODE_SECTION: YES
NETLIST_CONNECT_SECTION: YES
NETLIST_SUBCKT: YES
NETLIST_PASSIVE_PARAMS: YES
NETLIST_TAIL_COMMENTS: YES
NETLIST_DELIMITER: :
REDUCTION: NO
XREF: YES
EXTRACT_VIA_CAPS: NO
IGNORE_CAPACITANCE: NONE
KEEP_VIA_NODES: NO
MAGNIFICATION_FACTOR: 1.0
MAGNIFY_DEVICE_PARAMS: YES
METAL_FILL_POLYGON_HANDLING: IGNORE
MODE: 200
MOS_GATE_DELTA_RESISTANCE: NO
REMOVE_DANGLING_NETS: NO
REMOVE_FLOATING_NETS: NO
TRANSLATE_RETAIN_BULK_LAYERS: YES
SKIP_CELLS: !*
HIERARCHICAL_SEPARATOR: |
OBSERVATION_POINTS: *
EXTRA_GEOMETRY_INFO: NODE


OA_LIB_NAME: testLib
OA_VIEW_NAME: starrc
OA_MARKER_SIZE: 0.1
OA_REMOVE_SPICECARD_PREFIX: NO
OA_DEVICE_MAPPING_FILE: ../saed32nm_1p9m_device.map
OA_LAYER_MAPPING_FILE: ../saed32nm_1p9m_output_layer.map






