controls(
techParams(
;( parameter           value )
;( ----------             ----- )
( maskGrid          0.001 )
( MPPS              (list ( list nil ( quote cwW ) 0.09 ( quote cwL ) 0.09 ( quote cwSp ) 0.10 ( quote cwRowSp ) 0.15 ( quote Cw ) "CO" ( quote M1 ) "M1" ( quote M1CwEnc ) 0.005 ) ( list nil ( quote name ) "NWELL" ( quote pathLayer ) "DIFF" ( quote pathWidth ) 0.09 ( quote pathCwEnc ) 0.05 ( quote enclosureLayers ) ( list ) ( quote spacings ) ( list nil ) ) ( list nil ( quote name ) "sub" ( quote pathLayer ) "DIFF" ( quote pathWidth ) 0.09 ( quote pathCwEnc ) 0.05 ( quote enclosureLayers ) ( list ) ( quote spacings ) ( list nil ) ) ) )
( scale             1 )
( mfgGrid           0.001 )
( drcGrid           0.001 )
( cadGrid           0.001 )
);techParams

viewTypeUnits(
;( viewType                userUnit        DBUPerUU )
;( --------                     --------           -- --------   )
  ( maskLayout		 micron 	1000	)
  ( schematic		 inch 	160	)
  ( schematicSymbol	 inch 	160	)
  ( netlist		 inch 	160	)
) ;viewTypeUnits

  mfgGridResolution(
    ( 0.001 )
  ) ;mfgGridResolution

leMPPControls (
; leMPPDefinition ( name           objList               spacings          masterIndex        [(exposedParameters)]) 
;                            ( -----             -------                ---------            ------------           ---------------------) 
leMPPDefinition ( psubGR	( ptypeGuardRing )      ( 1 ) 	0 )

;leMPPRingObject (
;		name  masterPathName
;		enclosedPathNames
;		offsetPathNames
;		subRectangleNames
;		encShapeNames
;		netName
;		[exposedParameters]
;		-------------------------- )
leMPPRingObject (
		ptypeGuardRing defaultPath
		( diffEncPath pplusEncPath )
		nil 
		( defaultContacts )
		nil 
		vss
		userParams( name netName )
);leMppRingObject

; leMPPDefinition ( name           objList               spacings          masterIndex        [(exposedParameters)]) 
;                            ( -----             -------                ---------            ------------           ---------------------) 
leMPPDefinition ( nwellGR	( ntypeGuardRing )      ( 1 ) 	0 )

;leMPPRingObject (
;		name  masterPathName
;		enclosedPathNames
;		offsetPathNames
;		subRectangleNames
;		encShapeNames
;		netName
;		[exposedParameters]
;		-------------------------- )
leMPPRingObject (
		ntypeGuardRing defaultPath
		( diffEncPath nplusEncPath nwellEncPath )
		nil 
		( defaultContacts )
		nil 
		vdd
		userParams( name netName )
);leMppRingObject

;leMPPMasterPath (
;		name
;		layer   purpose
;		width   pathStyle  conn   chop
;		[exposedParameters]
;		----------------------- )
leMPPMasterPath (
		defaultPath
		M1   drawing
		0.05   extend t t
		userParams( name width layer purpose conn chop )
);leMPPMasterPath

;leMPPEnclosedPath (
;		name
;		layer   purpose
;		enclosure   pathStyle  conn   chop
;		[exposedParameters]
;		----------------------- )
leMPPEnclosedPath (
		diffEncPath
		DIFF   drawing
		0.016  extend t nil
		userParams( name enclosure layer purpose conn chop )
);leMPPEnclosedPath

;leMPPEnclosedPath (
;		name
;		layer   purpose
;		enclosure   pathStyle  conn   chop
;		[exposedParameters]
;		----------------------- )
leMPPEnclosedPath (
		pplusEncPath
		PIMP   drawing
		0.06  extend t nil
		userParams( name enclosure layer purpose conn chop )
);leMPPEnclosedPath

;leMPPEnclosedPath (
;		name
;		layer   purpose
;		enclosure   pathStyle  conn   chop
;		[exposedParameters]
;		----------------------- )
leMPPEnclosedPath (
		nplusEncPath
		NIMP   drawing
		0.06  extend t nil
		userParams( name enclosure layer purpose conn chop )
);leMPPEnclosedPath

;leMPPEnclosedPath (
;		name
;		layer   purpose
;		enclosure   pathStyle  conn   chop
;		[exposedParameters]
;		----------------------- )
leMPPEnclosedPath (
		nwellEncPath
		NWELL   drawing
		0.1  extend t nil
		userParams( name enclosure layer purpose conn chop )
);leMPPEnclosedPath

;leMPPSubRect(
;		name
;		layer   purpose
;		width  height  conn   chop  enclosure  endOfLine   spacing   spacingType  numRows
;		[exposedParameters]
;		----------------------- )
leMPPSubRect (
		defaultContacts
		CO   drawing
		0.042   0.042 t t  0.004  0.035  0.05  fit  1
		userParams( name layer purpose width height conn chop minEnclosure eol spacing spaceType numRows )
);leMPPSubRect

) ;leMPPControls

) ;controls

layerDefinitions(
 techPurposes(
;( purposeName  purposeNum   abbreviation )
;(   -----------        ----------        ----------     )
( dmy0             0                       )
( dmy1             1                       )
( dmy2             2                       )
( dmy3             3                       )
( dmy4             4                       )
( waterMark        63                      )
( dummy            127                     )
( subnode          221                     )
( extract          222                     )
( fatal            223        fat          )
( critical         224        crt          )
( soCritical       225        scr          )
( soError          226        ser          )
( ackWarn          227        ack          )
( info             228        inf          )
( track            229        trk          )
( blockage         230                     )
( warning          234        wng          )
( tool1            235        tl1          )
( tool0            236        tl0          )
( label            237        lbl          )
( flight           238        flt          )
( error            239        err          )
( annotate         240        ant          )
( drawing1         241        dr1          )
( drawing2         242        dr2          )
( drawing3         243        dr3          )
( drawing4         244        dr4          )
( drawing5         245        dr5          )
( drawing6         246        dr6          )
( drawing7         247        dr7          )
( drawing8         248        dr8          )
( drawing9         249        dr9          )
( boundary         250        bnd          )
( pin              251        pin          )
( net              253                     )
( cell             254                     )
( all              255                     )
 ) ;techPurposes

 techLayers(
;( layerName  layerNum   abbreviation )
;(   ---------      --------      ------------ )
( NWELL            1          NWELL        )
( DNW              2          DNW          )
( DIFF             3          DIFF         )
( PIMP             4          PIMP         )
( NIMP             5          NIMP         )
( DIFF_18          6          DIFF_18      )
( PAD              7          PAD          )
( ESD_25           8          ESD_25       )
( SBLK             9          SBLK         )
( PO               10         PO           )
( M1               11         M1           )
( VIA1             12         VIA1         )
( M2               13         M2           )
( VIA2             14         VIA2         )
( M3               15         M3           )
( VIA3             16         VIA3         )
( M4               17         M4           )
( VIA4             18         VIA4         )
( M5               19         M5           )
( VIA5             20         VIA5         )
( M6               21         M6           )
( VIA6             22         VIA6         )
( M7               23         M7           )
( VIA7             24         VIA7         )
( M8               25         M8           )
( VIA8             26         VIA8         )
( M9               27         M9           )
( CO               28         CO           )
( HVTIMP           29         HVTIMP       )
( LVTIMP           30         LVTIMP       )
( M1PIN            31         M1PIN        )
( M2PIN            32         M2PIN        )
( M3PIN            33         M3PIN        )
( M4PIN            34         M4PIN        )
( M5PIN            35         M5PIN        )
( M6PIN            36         M6PIN        )
( M7PIN            37         M7PIN        )
( M8PIN            38         M8PIN        )
( M9PIN            39         M9PIN        )
( MRDL             41         MRDL         )
( VIARDL           42         VIARDL       )
( MRPIN            43         MRPIN        )
( HOTNWL           44         HOTNWL       )
( DIOD             46         DIOD         )
( BJTMY            47         BJTMY        )
( RNW              48         RNW          )
( RMARK            49         RMARK        )
( PrBoundary       50         PrBoundary   )
( LOGO             51         LOGO         )
( IP               52         IP           )
( RM1              53         RM1          )
( RM2              54         RM2          )
( RM3              55         RM3          )
( RM4              56         RM4          )
( RM5              57         RM5          )
( RM6              58         RM6          )
( RM7              59         RM7          )
( RM8              60         RM8          )
( RM9              61         RM9          )
( DM1EXCL          64         DM1EXCL      )
( DM2EXCL          65         DM2EXCL      )
( DM3EXCL          66         DM3EXCL      )
( DM4EXCL          67         DM4EXCL      )
( DM5EXCL          68         DM5EXCL      )
( DM6EXCL          69         DM6EXCL      )
( DM7EXCL          70         DM7EXCL      )
( DM8EXCL          71         DM8EXCL      )
( DM9EXCL          72         DM9EXCL      )
( DIFFEXCL         73         DIFFEXCL     )
( POEXCL           74         POEXCL       )
( DIFF_25          75         DIFF_25      )
( Unrouted         200        Unroute      )
( Row              201        Row          )
( Group            202        Group        )
( Cannotoccupy     203        noOcupy      )
( Canplace         204        Canplac      )
( hardFence        205        hardFnc      )
( softFence        206        softFnc      )
( y0               207        y0           )
( y1               208        y1           )
( y2               209        y2           )
( y3               210        y3           )
( y4               211        y4           )
( y5               212        y5           )
( y6               213        y6           )
( y7               214        y7           )
( y8               215        y8           )
( y9               216        y9           )
( designFlow       217        dsnFlow      )
( stretch          218        stretch      )
( edgeLayer        219        edgeLyr      )
( changedLayer     220        chngLyr      )
( unset            221        unset        )
( unknown          222        unknown      )
( spike            223        spike        )
( hiz              224        hiz          )
( resist           225        resist       )
( drive            226        drive        )
( supply           227        supply       )
( wire             228        wire         )
( pin              229        pin          )
( text             230        text         )
( device           231        device       )
( border           232        border       )
( snap             233        snap         )
( align            234        align        )
( prBoundary       235        prBndry      )
( instance         236        instnce      )
( annotate         237        anotate      )
( marker           238        marker       )
( select           239        select       )
( grid             251        grid         )
( axis             252        axis         )
( hilite           253        hilite       )
( background       254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
;(  layerName   purposeName  )
;(   ---------        ------------     )
( NWELL            drawing          )
( DNW              drawing          )
( DIFF             drawing          )
( PIMP             drawing          )
( NIMP             drawing          )
( DIFF_18          drawing          )
( PAD              drawing          )
( ESD_25           drawing          )
( SBLK             drawing          )
( PO               drawing          )
( M1               drawing          )
( M2               drawing          )
( M3               drawing          )
( M4               drawing          )
( M5               drawing          )
( M6               drawing          )
( M7               drawing          )
( M8               drawing          )
( M9               drawing          )
( CO               drawing          )
( VIA1             drawing          )
( VIA2             drawing          )
( VIA3             drawing          )
( VIA4             drawing          )
( VIA5             drawing          )
( VIA6             drawing          )
( VIA7             drawing          )
( VIA8             drawing          )
( HVTIMP           drawing          )
( LVTIMP           drawing          )
( M1PIN            drawing          )
( M2PIN            drawing          )
( M3PIN            drawing          )
( M4PIN            drawing          )
( M5PIN            drawing          )
( M6PIN            drawing          )
( M7PIN            drawing          )
( M8PIN            drawing          )
( M9PIN            drawing          )
( MRDL             drawing          )
( VIARDL           drawing          )
( MRPIN            drawing          )
( HOTNWL           drawing          )
( DIOD             drawing          )
( BJTMY            drawing          )
( RNW              drawing          )
( RMARK            drawing          )
( LOGO             drawing          )
( IP               drawing          )
( PrBoundary       drawing          )
( RM1              drawing          )
( RM2              drawing          )
( RM3              drawing          )
( RM4              drawing          )
( RM5              drawing          )
( RM6              drawing          )
( RM7              drawing          )
( RM8              drawing          )
( RM9              drawing          )
( DM1EXCL          drawing          )
( DM2EXCL          drawing          )
( DM3EXCL          drawing          )
( DM4EXCL          drawing          )
( DM5EXCL          drawing          )
( DM6EXCL          drawing          )
( DM7EXCL          drawing          )
( DM8EXCL          drawing          )
( DM9EXCL          drawing          )
( DIFFEXCL         drawing          )
( POEXCL           drawing          )
( DIFF_25          drawing          )
( Cannotoccupy     boundary         )
( Cannotoccupy     drawing          )
( Canplace         drawing          )
( Group            boundary         )
( Group            drawing          )
( Group            label            )
( Row              boundary         )
( Row              drawing          )
( Row              label            )
( Unrouted         drawing          )
( Unrouted         drawing1         )
( Unrouted         drawing2         )
( Unrouted         drawing3         )
( Unrouted         drawing4         )
( Unrouted         drawing5         )
( Unrouted         drawing6         )
( Unrouted         drawing7         )
( Unrouted         drawing8         )
( Unrouted         drawing9         )
( Unrouted         track            )
( align            drawing          )
( annotate         drawing          )
( annotate         drawing1         )
( annotate         drawing2         )
( annotate         drawing3         )
( annotate         drawing4         )
( annotate         drawing5         )
( annotate         drawing6         )
( annotate         drawing7         )
( annotate         drawing8         )
( annotate         drawing9         )
( axis             drawing          )
( background       drawing          )
( border           boundary         )
( border           drawing          )
( changedLayer     tool0            )
( changedLayer     tool1            )
( designFlow       drawing          )
( designFlow       drawing1         )
( designFlow       drawing2         )
( designFlow       drawing3         )
( designFlow       drawing4         )
( designFlow       drawing5         )
( designFlow       drawing6         )
( designFlow       drawing7         )
( designFlow       drawing8         )
( designFlow       drawing9         )
( device           annotate         )
( device           drawing          )
( device           drawing1         )
( device           drawing2         )
( device           label            )
( drive            drawing          )
( edgeLayer        drawing          )
( edgeLayer        pin              )
( grid             drawing          )
( grid             drawing1         )
( hardFence        drawing          )
( hilite           drawing          )
( hilite           drawing1         )
( hilite           drawing2         )
( hilite           drawing3         )
( hilite           drawing4         )
( hilite           drawing5         )
( hilite           drawing6         )
( hilite           drawing7         )
( hilite           drawing8         )
( hilite           drawing9         )
( hiz              drawing          )
( instance         drawing          )
( instance         label            )
( marker           ackWarn          )
( marker           annotate         )
( marker           critical         )
( marker           error            )
( marker           fatal            )
( marker           info             )
( marker           soCritical       )
( marker           soError          )
( marker           warning          )
( pin              annotate         )
( pin              drawing          )
( pin              label            )
( prBoundary       boundary         )
( prBoundary       drawing          )
( prBoundary       label            )
( resist           drawing          )
( select           drawing          )
( snap             boundary         )
( snap             drawing          )
( softFence        drawing          )
( spike            drawing          )
( stretch          drawing          )
( supply           drawing          )
( text             drawing          )
( text             drawing1         )
( text             drawing2         )
( unknown          drawing          )
( unset            drawing          )
( wire             drawing          )
( wire             flight           )
( wire             label            )
( y0               drawing          )
( y0               flight           )
( y1               drawing          )
( y1               flight           )
( y2               drawing          )
( y2               flight           )
( y3               drawing          )
( y3               flight           )
( y4               drawing          )
( y4               flight           )
( y5               drawing          )
( y5               flight           )
( y6               drawing          )
( y6               flight           )
( y7               drawing          )
( y7               flight           )
( y8               drawing          )
( y8               flight           )
( y9               drawing          )
( y9               flight           )
) ;techLayerPurposePriorities

techDisplays(
;(lLayerName purposeName  packet  vis sel   con2ChgLy   drgEnbl  valid )
;(   ---------        -------           ------   --- ---    ------------     -------    ----- )
( NWELL            drawing          NWELL           	t t nil t t  )
( DNW              drawing          DNW             	t t nil t t  )
( DIFF             drawing          DIFF            	t t nil t t  )
( PIMP             drawing          PIMP            	t t nil t t  )
( NIMP             drawing          NIMP            	t t nil t t  )
( DIFF_18          drawing          DIFF_18         	t t nil t t  )
( PAD              drawing          PAD             	t t nil t t  )
( ESD_25           drawing          ESD_25          	t t nil t t  )
( SBLK             drawing          SBLK            	t t nil t t  )
( PO               drawing          PO              	t t nil t t  )
( M1               drawing          M1              	t t nil t t  )
( M2               drawing          M2              	t t nil t t  )
( M3               drawing          M3              	t t nil t t  )
( M4               drawing          M4              	t t nil t t  )
( M5               drawing          M5              	t t nil t t  )
( M6               drawing          M6              	t t nil t t  )
( M7               drawing          M7              	t t nil t t  )
( M8               drawing          M8              	t t nil t t  )
( M9               drawing          M9              	t t nil t t  )
( CO               drawing          CO              	t t nil t t  )
( VIA1             drawing          VIA1            	t t nil t t  )
( VIA2             drawing          VIA2            	t t nil t t  )
( VIA3             drawing          VIA3            	t t nil t t  )
( VIA4             drawing          VIA4            	t t nil t t  )
( VIA5             drawing          VIA5            	t t nil t t  )
( VIA6             drawing          VIA6            	t t nil t t  )
( VIA7             drawing          VIA7            	t t nil t t  )
( VIA8             drawing          VIA8            	t t nil t t  )
( HVTIMP           drawing          HVTIMP          	t t nil t t  )
( LVTIMP           drawing          LVTIMP          	t t nil t t  )
( M1PIN            drawing          M1PIN           	t t nil t t  )
( M2PIN            drawing          M2PIN           	t t nil t t  )
( M3PIN            drawing          M3PIN           	t t nil t t  )
( M4PIN            drawing          M4PIN           	t t nil t t  )
( M5PIN            drawing          M5PIN           	t t nil t t  )
( M6PIN            drawing          M6PIN           	t t nil t t  )
( M7PIN            drawing          M7PIN           	t t nil t t  )
( M8PIN            drawing          M8PIN           	t t nil t t  )
( M9PIN            drawing          M9PIN           	t t nil t t  )
( MRDL             drawing          MRDL            	t t nil t t  )
( VIARDL           drawing          VIARDL          	t t nil t t  )
( MRPIN            drawing          MRPIN           	t t nil t t  )
( HOTNWL           drawing          HOTNWL          	t t nil t t  )
( DIOD             drawing          DIOD            	t t nil t t  )
( BJTMY            drawing          BJTMY           	t t nil t t  )
( RNW              drawing          RNW             	t t nil t t  )
( RMARK            drawing          RMARK           	t t nil t t  )
( LOGO             drawing          LOGO            	t t nil t t  )
( IP               drawing          IP              	t t nil t t  )
( PrBoundary       drawing          PrBoundary      	t t nil t t  )
( RM1              drawing          RM1             	t t nil t t  )
( RM2              drawing          RM2             	t t nil t t  )
( RM3              drawing          RM3             	t t nil t t  )
( RM4              drawing          RM4             	t t nil t t  )
( RM5              drawing          RM5             	t t nil t t  )
( RM6              drawing          RM6             	t t nil t t  )
( RM7              drawing          RM7             	t t nil t t  )
( RM8              drawing          RM8             	t t nil t t  )
( RM9              drawing          RM9             	t t nil t t  )
( DM1EXCL          drawing          DM1EXCL         	t t nil t t  )
( DM2EXCL          drawing          DM2EXCL         	t t nil t t  )
( DM3EXCL          drawing          DM3EXCL         	t t nil t t  )
( DM4EXCL          drawing          DM4EXCL         	t t nil t t  )
( DM5EXCL          drawing          DM5EXCL         	t t nil t t  )
( DM6EXCL          drawing          DM6EXCL         	t t nil t t  )
( DM7EXCL          drawing          DM7EXCL         	t t nil t t  )
( DM8EXCL          drawing          DM8EXCL         	t t nil t t  )
( DM9EXCL          drawing          DM9EXCL         	t t nil t t  )
( DIFFEXCL         drawing          DIFFEXCL        	t t nil t t  )
( POEXCL           drawing          POEXCL          	t t nil t t  )
( DIFF_25          drawing          DIFF_25         	t t nil t t  )
( Cannotoccupy     boundary         CannotoccupyBnd 	t t t t nil  )
( Cannotoccupy     drawing          Cannotoccupy    	t t t t nil  )
( Canplace         drawing          Canplace        	t t t t nil  )
( Group            boundary         GroupBnd        	t nil t t nil  )
( Group            drawing          Group           	t t t t nil  )
( Group            label            GroupLbl        	t nil t t nil  )
( Row              boundary         RowBnd          	t t t t nil  )
( Row              drawing          Row             	t t t t nil  )
( Row              label            RowLbl          	t nil t t nil  )
( Unrouted         drawing          Unrouted        	t t t t nil  )
( Unrouted         drawing1         Unrouted1       	t t t t nil  )
( Unrouted         drawing2         Unrouted2       	t t t t nil  )
( Unrouted         drawing3         Unrouted3       	t t t t nil  )
( Unrouted         drawing4         Unrouted4       	t t t t nil  )
( Unrouted         drawing5         Unrouted5       	t t t t nil  )
( Unrouted         drawing6         Unrouted6       	t t t t nil  )
( Unrouted         drawing7         Unrouted7       	t t t t nil  )
( Unrouted         drawing8         Unrouted8       	t t t t nil  )
( Unrouted         drawing9         Unrouted9       	t t t t nil  )
( Unrouted         track            UnroutedTrk     	t t t t nil  )
( align            drawing          align           	t t t t nil  )
( annotate         drawing          annotate        	t t t t nil  )
( annotate         drawing1         annotate1       	t t t t nil  )
( annotate         drawing2         annotate2       	t t t t nil  )
( annotate         drawing3         annotate3       	t t t t nil  )
( annotate         drawing4         annotate4       	t t t t nil  )
( annotate         drawing5         annotate5       	t t t t nil  )
( annotate         drawing6         annotate6       	t t t t nil  )
( annotate         drawing7         annotate7       	t t t t nil  )
( annotate         drawing8         annotate8       	t t t t nil  )
( annotate         drawing9         annotate9       	nil t t t nil  )
( axis             drawing          axis            	t nil t t nil  )
( background       drawing          background      	t nil t nil nil  )
( border           boundary         area            	t nil t t nil  )
( border           drawing          border          	t t t t nil  )
( changedLayer     tool0            changedLayerTl0 	nil nil t nil nil  )
( changedLayer     tool1            changedLayerTl1 	nil nil t nil nil  )
( designFlow       drawing          designFlow      	t t t nil nil  )
( designFlow       drawing1         designFlow1     	t t t nil nil  )
( designFlow       drawing2         designFlow2     	t t t nil nil  )
( designFlow       drawing3         designFlow3     	t t t nil nil  )
( designFlow       drawing4         designFlow4     	t t t nil nil  )
( designFlow       drawing5         designFlow5     	t t t nil nil  )
( designFlow       drawing6         designFlow6     	t t t nil nil  )
( designFlow       drawing7         designFlow7     	t t t nil nil  )
( designFlow       drawing8         designFlow8     	t t t nil nil  )
( designFlow       drawing9         designFlow9     	t t t nil nil  )
( device           annotate         deviceAnt       	t t t t nil  )
( device           drawing          device          	t t t t nil  )
( device           drawing1         device1         	t t t t nil  )
( device           drawing2         device2         	t t t t nil  )
( device           label            deviceLbl       	t t t t nil  )
( drive            drawing          drive           	t t t t nil  )
( edgeLayer        drawing          edgeLayer       	t t t t nil  )
( edgeLayer        pin              edgeLayerPin    	t t t t nil  )
( grid             drawing          grid            	t nil t nil nil  )
( grid             drawing1         grid1           	t nil t nil nil  )
( hardFence        drawing          hardFence       	t t t t nil  )
( hilite           drawing          hilite          	t t t t nil  )
( hilite           drawing1         hilite1         	t t t t nil  )
( hilite           drawing2         hilite2         	t t t t nil  )
( hilite           drawing3         hilite3         	t t t t nil  )
( hilite           drawing4         hilite4         	t t t t nil  )
( hilite           drawing5         hilite5         	t t t t nil  )
( hilite           drawing6         hilite6         	t t t t nil  )
( hilite           drawing7         hilite7         	t t t t nil  )
( hilite           drawing8         hilite8         	t t t t nil  )
( hilite           drawing9         hilite9         	t t t t nil  )
( hiz              drawing          hiz             	t t t t nil  )
( instance         drawing          instance        	t t t t nil  )
( instance         label            instanceLbl     	t t t t nil  )
( marker           ackWarn          markerAck       	t t t t nil  )
( marker           annotate         markerAno       	t t t t nil  )
( marker           critical         markerCrt       	t t t t nil  )
( marker           error            markerErr       	t t t t nil  )
( marker           fatal            markerFat       	t t t t nil  )
( marker           info             markerInf       	t t t t nil  )
( marker           soCritical       markerScr       	t t t t nil  )
( marker           soError          markerSer       	t t t t nil  )
( marker           warning          markerWarn      	t t t t nil  )
( pin              annotate         pinAnt          	t t t t nil  )
( pin              drawing          pin             	t t t t nil  )
( pin              label            pinLbl          	t t t t nil  )
( prBoundary       boundary         prBoundaryBnd   	t t t t nil  )
( prBoundary       drawing          prBoundary      	t t t t nil  )
( prBoundary       label            prBoundaryLbl   	t t t t nil  )
( resist           drawing          resist          	t t t t nil  )
( select           drawing          select          	t t t t nil  )
( snap             boundary         snap            	t nil t t nil  )
( snap             drawing          snap            	t t t t nil  )
( softFence        drawing          softFence       	t t t t nil  )
( spike            drawing          spike           	t t t t nil  )
( stretch          drawing          stretch         	t t t t nil  )
( supply           drawing          supply          	t t t t nil  )
( text             drawing          text            	t t t t t  )
( text             drawing1         text1           	t t t t nil  )
( text             drawing2         text2           	t t t t nil  )
( unknown          drawing          unknown         	t t t t nil  )
( unset            drawing          unset           	t t t t nil  )
( wire             drawing          wire            	t t t t nil  )
( wire             flight           wireFlt         	t t t t nil  )
( wire             label            wireLbl         	t t t t nil  )
( y0               drawing          y0              	t t t t nil  )
( y0               flight           y0Flt           	t t t t nil  )
( y1               drawing          y1              	t t t t nil  )
( y1               flight           y1Flt           	t t t t nil  )
( y2               drawing          y2              	t t t t nil  )
( y2               flight           y2Flt           	t t t t nil  )
( y3               drawing          y3              	t t t t nil  )
( y3               flight           y3Flt           	t t t t nil  )
( y4               drawing          y4              	t t t t nil  )
( y4               flight           y4Flt           	t t t t nil  )
( y5               drawing          y5              	t t t t nil  )
( y5               flight           y5Flt           	t t t t nil  )
( y6               drawing          y6              	t t t t nil  )
( y6               flight           y6Flt           	t t t t nil  )
( y7               drawing          y7              	t t t t nil  )
( y7               flight           y7Flt           	t t t t nil  )
( y8               drawing          y8              	t t t t nil  )
( y8               flight           y8Flt           	t t t t nil  )
( y9               drawing          y9              	t t t t nil  )
( y9               flight           y9Flt           	t t t t nil  )
) ;techDisplays

 techLayerProperties(
;( propName     layer1/lpp1  [layer2/lpp2]      propValue )
;( --------            ------           ----------            ---------   )
( sheetResistance  DIFF            	 0.001 )
( sheetResistance  PO              	 15 )
( sheetResistance  M1              	 0.1 )
( sheetResistance  VIA1            	 1.5 )
( sheetResistance  M2              	 0.1 )
( sheetResistance  VIA2            	 1.5 )
( sheetResistance  M3              	 0.1 )
( sheetResistance  VIA3            	 1.5 )
( sheetResistance  M4              	 0.1 )
( sheetResistance  VIA4            	 1.5 )
( sheetResistance  M5              	 0.1 )
( sheetResistance  VIA5            	 1.5 )
( sheetResistance  M6              	 0.1 )
( sheetResistance  VIA6            	 1.5 )
( sheetResistance  M7              	 0.1 )
( sheetResistance  VIA7            	 1.5 )
( sheetResistance  M8              	 0.1 )
( sheetResistance  VIA8            	 0.1 )
( sheetResistance  M9              	 0.28 )
( sheetResistance  MRDL            	 0.35 )
( sheetResistance  VIARDL          	 0.05 )
 ) ;techLayerProperties

) ;layerDefinitions

layerRules(
 functions(
;( layer     function     [maskNumber])
;( -----      --------        ------------    )
( NWELL             nWell         1 )
( DNW               other         38 )
( DIFF              diffusion     2 )
( PIMP              pImplant      5 )
( NIMP              nImplant      6 )
( DIFF_18           diffusion     3 )
( PAD               other         55 )
( ESD_25            other         39 )
( SBLK              other         69 )
( PO                other         56 )
( M1                metal         7 )
( VIA1              cut           8 )
( M2                metal         9 )
( VIA2              cut           10 )
( M3                metal         11 )
( VIA3              cut           12 )
( M4                metal         13 )
( VIA4              cut           14 )
( M5                metal         15 )
( VIA5              cut           16 )
( M6                metal         17 )
( VIA6              cut           18 )
( M7                metal         19 )
( VIA7              cut           24 )
( M8                metal         20 )
( VIA8              cut           25 )
( M9                metal         21 )
( CO                cut           26 )
( HVTIMP            other         41 )
( LVTIMP            other         44 )
( M1PIN             other         45 )
( M2PIN             other         46 )
( M3PIN             other         47 )
( M4PIN             other         48 )
( M5PIN             other         49 )
( M6PIN             other         50 )
( M7PIN             other         51 )
( M8PIN             other         52 )
( M9PIN             other         53 )
( MRDL              metal         22 )
( VIARDL            cut           23 )
( MRPIN             other         54 )
( HOTNWL            other         40 )
( DIOD              other         28 )
( BJTMY             other         27 )
( RNW               other         66 )
( RMARK             other         67 )
( PrBoundary        other         70 )
( LOGO              other         43 )
( IP                other         42 )
( RM1               other         57 )
( RM2               other         58 )
( RM3               other         59 )
( RM4               other         60 )
( RM5               other         61 )
( RM6               other         62 )
( RM7               other         63 )
( RM8               other         64 )
( RM9               other         65 )
( DM1EXCL           other         29 )
( DM2EXCL           other         30 )
( DM3EXCL           other         31 )
( DM4EXCL           other         32 )
( DM5EXCL           other         33 )
( DM6EXCL           other         34 )
( DM7EXCL           other         35 )
( DM8EXCL           other         36 )
( DM9EXCL           other         37 )
( DIFF_25           diffusion     4 )
 ) ;functions

 mfgResolutions(
;( layer         mfgResolution )
;( -----           -------------    )
( NWELL              0.001 )
( DNW                0.001 )
( DIFF               0.001 )
( PIMP               0.001 )
( NIMP               0.001 )
( DIFF_18            0.001 )
( PAD                0.001 )
( ESD_25             0.001 )
( SBLK               0.001 )
( PO                 0.001 )
( M1                 0.001 )
( VIA1               0.001 )
( M2                 0.001 )
( VIA2               0.001 )
( M3                 0.001 )
( VIA3               0.001 )
( M4                 0.001 )
( VIA4               0.001 )
( M5                 0.001 )
( VIA5               0.001 )
( M6                 0.001 )
( VIA6               0.001 )
( M7                 0.001 )
( VIA7               0.001 )
( M8                 0.001 )
( VIA8               0.001 )
( M9                 0.001 )
( CO                 0.001 )
( HVTIMP             0.001 )
( LVTIMP             0.001 )
( M1PIN              0.001 )
( M2PIN              0.001 )
( M3PIN              0.001 )
( M4PIN              0.001 )
( M5PIN              0.001 )
( M6PIN              0.001 )
( M7PIN              0.001 )
( M8PIN              0.001 )
( M9PIN              0.001 )
( MRDL               0.001 )
( VIARDL             0.001 )
( MRPIN              0.001 )
( HOTNWL             0.001 )
( DIOD               0.001 )
( BJTMY              0.001 )
( RNW                0.001 )
( RMARK              0.001 )
( PrBoundary         0.001 )
( LOGO               0.001 )
( IP                 0.001 )
( RM1                0.001 )
( RM2                0.001 )
( RM3                0.001 )
( RM4                0.001 )
( RM5                0.001 )
( RM6                0.001 )
( RM7                0.001 )
( RM8                0.001 )
( RM9                0.001 )
( DM1EXCL            0.001 )
( DM2EXCL            0.001 )
( DM3EXCL            0.001 )
( DM4EXCL            0.001 )
( DM5EXCL            0.001 )
( DM6EXCL            0.001 )
( DM7EXCL            0.001 )
( DM8EXCL            0.001 )
( DM9EXCL            0.001 )
( DIFFEXCL           0.001 )
( POEXCL             0.001 )
( DIFF_25            0.001 )
( Unrouted           0.001 )
( Row                0.001 )
( Group              0.001 )
( Cannotoccupy       0.001 )
( Canplace           0.001 )
( hardFence          0.001 )
( softFence          0.001 )
( y0                 0.001 )
( y1                 0.001 )
( y2                 0.001 )
( y3                 0.001 )
( y4                 0.001 )
( y5                 0.001 )
( y6                 0.001 )
( y7                 0.001 )
( y8                 0.001 )
( y9                 0.001 )
( designFlow         0.001 )
( stretch            0.001 )
( edgeLayer          0.001 )
( changedLayer       0.001 )
( unset              0.001 )
( unknown            0.001 )
( spike              0.001 )
( hiz                0.001 )
( resist             0.001 )
( drive              0.001 )
( supply             0.001 )
( wire               0.001 )
( pin                0.001 )
( text               0.001 )
( device             0.001 )
( border             0.001 )
( snap               0.001 )
( align              0.001 )
( prBoundary         0.001 )
( instance           0.001 )
( annotate           0.001 )
( marker             0.001 )
( select             0.001 )
( grid               0.001 )
( axis               0.001 )
( hilite             0.001 )
( background         0.001 )
 ) ;mfgResolutions

 routingDirections(
;( layer         direction  )
;( -----          --------    )
( M1 	horizontal )
( M2 	vertical )
( M3 	horizontal )
( M4 	vertical )
( M5 	horizontal )
( M6 	vertical )
( M7 	horizontal )
( M8 	vertical )
( M9 	horizontal )
( MRDL 	vertical )
 ) ;routingDirections

) ;layerRules

 viaDefs(
standardViaDefs(
;(viaDefName  layer1  layer2  (cutLayer cutWidth cutHeight [resistancePerCut])
;(cutRows   cutCol  (cutSpacing))
;(layer1Enc) (layer2Enc) (layer1Offset)  (layer2Offset)  (origOffset)
;[implant1   (implant1Enc)  [implant2  (implant2Enc)]])
;( -------------------------------------------------------------------------- )
(DIFFCON          DIFF         M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.02 0.01 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(DIFFCONC         DIFF         M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.01 0.02 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(POLYCON1         PO           M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.05 0.02 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(POLYCON1C        PO           M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.02 0.05 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(POLYCON2         PO           M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.034 0.02 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(POLYCON2C        PO           M1           ( CO          0.042 0.042 0 ) 
 (1 1 ( 0.05 0.05 )  )
 ( 0.02 0.034 )  ( 0.035 0.004 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12            M1           M2           ( VIA1        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12C           M1           M2           ( VIA1        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12BAR         M1           M2           ( VIA1        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12BARC        M1           M2           ( VIA1        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12LG          M1           M2           ( VIA1        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA12LGC         M1           M2           ( VIA1        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23            M2           M3           ( VIA2        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23C           M2           M3           ( VIA2        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23BAR         M2           M3           ( VIA2        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23BARC        M2           M3           ( VIA2        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23LG          M2           M3           ( VIA2        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA23LGC         M2           M3           ( VIA2        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34            M3           M4           ( VIA3        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34C           M3           M4           ( VIA3        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34BAR         M3           M4           ( VIA3        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34BARC        M3           M4           ( VIA3        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34LG          M3           M4           ( VIA3        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA34LGC         M3           M4           ( VIA3        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45            M4           M5           ( VIA4        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45C           M4           M5           ( VIA4        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45BAR         M4           M5           ( VIA4        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45BARC        M4           M5           ( VIA4        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45LG          M4           M5           ( VIA4        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA45LGC         M4           M5           ( VIA4        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56            M5           M6           ( VIA5        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56C           M5           M6           ( VIA5        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56BAR         M5           M6           ( VIA5        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56BARC        M5           M6           ( VIA5        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56LG          M5           M6           ( VIA5        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA56LGC         M5           M6           ( VIA5        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67            M6           M7           ( VIA6        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67C           M6           M7           ( VIA6        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67BAR         M6           M7           ( VIA6        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67BARC        M6           M7           ( VIA6        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67LG          M6           M7           ( VIA6        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA67LGC         M6           M7           ( VIA6        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78            M7           M8           ( VIA7        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78C           M7           M8           ( VIA7        0.05 0.05 1.5 ) 
 (1 1 ( 0.07 0.07 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78BAR         M7           M8           ( VIA7        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78BARC        M7           M8           ( VIA7        0.05 0.1 1 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78LG          M7           M8           ( VIA7        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.03 0.005 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA78LGC         M7           M8           ( VIA7        0.1 0.1 0.5 ) 
 (1 1 ( 0.085 0.085 )  )
 ( 0.005 0.03 )  ( 0.03 0.005 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA89            M8           M9           ( VIA8        0.13 0.13 0.1 ) 
 (1 1 ( 0.12 0.12 )  )
 ( 0.03 0.015 )  ( 0.03 0.015 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIA89C           M8           M9           ( VIA8        0.13 0.13 0.1 ) 
 (1 1 ( 0.12 0.12 )  )
 ( 0.015 0.03 )  ( 0.03 0.015 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
(VIARDL           M9           MRDL         ( VIARDL      2 2 0.05 ) 
 (1 1 ( 2 2 )  )
 ( 0.05 0.05 )  ( 0.05 0.05 )  ( 0 0 )  ( 0 0 )  ( 0 0 )  )
) ;standardViaDefs

 ) ;viaDefs

constraintGroups (
;( groupName       [-operator op][-override true|false] //default operator value is precedence, default override value is false;
;( constraintName [layers/lpps]   contraintValue [params] [-isHard true|false] [-comment] )
;( constraintGroup referenceGroupName);
;-------------------------------------------------------- )
( foundry  
( minWidth	NWELL 	0.23 )
( minSpacing	NWELL 	0.23 )
( minDiffPotentialSpacing	NWELL 	0.46 )
( minArea	NWELL 	0.45 )
( minEnclosedArea	NWELL 	0.45 )
( minSpacing	DNW 	3.5 )
( minWidth	DNW 	3 )
( minWidth	DIFF 	0.044 )
( minSpacing	DIFF 	0.05 )
( minArea	DIFF 	0.02 )
( minEnclosedArea	DIFF 	0.03 )
( minWidth	DIFF_18 	0.33 )
( minSpacing	DIFF_18 	0.33 )
( minArea	DIFF_18 	0.4 )
( minEnclosedArea	DIFF_18 	0.4 )
( minWidth	PO 	0.03 )
( minSpacing	PO 	0.086 )
( minArea	PO 	0.012 )
( minWidth	PIMP 	0.17 )
( minSpacing	PIMP 	0.17 )
( minWidth	NIMP 	0.17 )
( minSpacing	NIMP 	0.17 )
( minWidth	CO 	0.042 )
( maxLength	CO 	0.042 )
( maxWidth	CO 	0.042 )
( minSpacing	CO 	0.05 )
( minWidth	M1 	0.05 )
( maxWidth	M1 	5 )
( minSpacing	M1 	0.05 )
( minArea	M1 	0.01 )
( minEnclosedArea	M1 	0.2 )
( minWidth	VIA1 	0.05 )
( maxLength	VIA1 	0.1 )
( maxWidth	VIA1 	0.1 )
( minSpacing	VIA1 	0.07 )
( minWidth	M2 	0.056 )
( maxWidth	M2 	5 )
( minSpacing	M2 	0.056 )
( minArea	M2 	0.016 )
( minEnclosedArea	M2 	0.2 )
( minWidth	VIA2 	0.05 )
( maxLength	VIA2 	0.1 )
( maxWidth	VIA2 	0.1 )
( minSpacing	VIA2 	0.07 )
( minWidth	M3 	0.056 )
( maxWidth	M3 	5 )
( minSpacing	M3 	0.056 )
( minArea	M3 	0.016 )
( minEnclosedArea	M3 	0.2 )
( minWidth	VIA3 	0.05 )
( maxLength	VIA3 	0.1 )
( maxWidth	VIA3 	0.1 )
( minSpacing	VIA3 	0.07 )
( minWidth	M4 	0.056 )
( maxWidth	M4 	5 )
( minSpacing	M4 	0.056 )
( minArea	M4 	0.016 )
( minEnclosedArea	M4 	0.2 )
( minWidth	VIA4 	0.05 )
( maxLength	VIA4 	0.1 )
( maxWidth	VIA4 	0.1 )
( minSpacing	VIA4 	0.07 )
( minWidth	M5 	0.056 )
( maxWidth	M5 	5 )
( minSpacing	M5 	0.056 )
( minArea	M5 	0.016 )
( minEnclosedArea	M5 	0.2 )
( minWidth	VIA5 	0.05 )
( maxLength	VIA5 	0.1 )
( maxWidth	VIA5 	0.1 )
( minSpacing	VIA5 	0.07 )
( minWidth	M6 	0.056 )
( maxWidth	M6 	5 )
( minSpacing	M6 	0.056 )
( minArea	M6 	0.016 )
( minEnclosedArea	M6 	0.2 )
( minWidth	VIA6 	0.05 )
( maxLength	VIA6 	0.1 )
( maxWidth	VIA6 	0.1 )
( minSpacing	VIA6 	0.07 )
( minWidth	M7 	0.056 )
( maxWidth	M7 	5 )
( minSpacing	M7 	0.056 )
( minArea	M7 	0.016 )
( minEnclosedArea	M7 	0.2 )
( minWidth	VIA7 	0.05 )
( maxLength	VIA7 	0.1 )
( maxWidth	VIA7 	0.1 )
( minSpacing	VIA7 	0.07 )
( minWidth	M8 	0.056 )
( maxWidth	M8 	5 )
( minSpacing	M8 	0.056 )
( minArea	M8 	0.016 )
( minEnclosedArea	M8 	0.2 )
( minWidth	VIA8 	0.13 )
( maxLength	VIA8 	0.13 )
( maxWidth	VIA8 	0.13 )
( minSpacing	VIA8 	0.12 )
( minWidth	M9 	0.16 )
( maxWidth	M9 	10 )
( minSpacing	M9 	0.16 )
( minArea	M9 	0.055 )
( minEnclosedArea	M9 	0.2 )
( minWidth	MRDL 	2 )
( maxWidth	MRDL 	30 )
( minSpacing	MRDL 	2 )
( minWidth	VIARDL 	2 )
( maxLength	VIARDL 	2 )
( maxWidth	VIARDL 	2 )
( minSpacing	VIARDL 	2 )
( minWidth	HVTIMP 	0.85 )
( minSpacing	HVTIMP 	0.85 )
( minWidth	LVTIMP 	0.85 )
( minSpacing	LVTIMP 	0.85 )
( minWidth	SBLK 	0.33 )
( minSpacing	SBLK 	0.33 )
( minWidth	DIFF_25 	0.33 )
( minSpacing	DIFF_25 	0.33 )
( minArea	DIFF_25 	0.4 )
( minEnclosedArea	DIFF_25 	0.4 )
( minClearance	NWELL DIFF 	0.065 )
( minClearance	PIMP DIFF 	0.02 )
( minClearance	NIMP DIFF 	0.02 )
( minClearance	DIFF_18 DIFF 	0.15 )
( minClearance	DIFF_25 DIFF 	0.15 )
( minClearance	M1 VIA1 	0.08 )
( minClearance	M2 VIA2 	0.08 )
( minClearance	M3 VIA3 	0.08 )
( minClearance	M4 VIA4 	0.08 )
( minClearance	M5 VIA5 	0.08 )
( minClearance	M6 VIA6 	0.08 )
( minClearance	M7 VIA7 	0.08 )
( minClearance	M8 VIA8 	0.08 )
( minClearance	CO PO 	0.04 )
( minClearance	CO DIFF 	0.04 )
( minClearance	CO SBLK 	0.13 )
( minClearance	DIFF PO 	0.035 )
( minClearance	NIMP PIMP 	0 )
( minEnclosure	PO DIFF 	0.08 )
( minEnclosure	DIFF_18 DIFF 	0.15 )
( minEnclosure	DIFF_25 DIFF 	0.15 )
( minClearance	NWELL DNW 	2.5 )
( minClearance	DNW DIFF 	1.5 )
( minClearance	SBLK DIFF 	0.18 )
( minClearance	SBLK PO 	0.3 )
( minEnclosure	NWELL DIFF 	0.065 )
( minEnclosure	M1 VIA1 	0.005 )
( minEnclosure	M2 VIA1 	0.005 )
( minEnclosure	M2 VIA2 	0.005 )
( minEnclosure	M3 VIA2 	0.005 )
( minEnclosure	M3 VIA3 	0.005 )
( minEnclosure	M4 VIA3 	0.005 )
( minEnclosure	M4 VIA4 	0.005 )
( minEnclosure	M5 VIA4 	0.005 )
( minEnclosure	M5 VIA5 	0.005 )
( minEnclosure	M6 VIA5 	0.005 )
( minEnclosure	M6 VIA6 	0.005 )
( minEnclosure	M7 VIA6 	0.005 )
( minEnclosure	M7 VIA7 	0.005 )
( minEnclosure	M8 VIA7 	0.005 )
( minEnclosure	NWELL DNW 	1 )
( minEnclosure	M8 VIA8 	0.015 )
( minEnclosure	M9 VIA8 	0.015 )
( minEnclosure	MRDL VIARDL 	0.5 )
( minEnclosure	PIMP DIFF 	0.02 )
( minEnclosure	NIMP DIFF 	0.02 )
( minEnclosure	HVTIMP DIFF 	0.05 )
( minEnclosure	LVTIMP DIFF 	0.05 )
( minEnclosure	SBLK DIFF 	0.18 )
( minEnclosure	PO SBLK 	0.18 )
( minEnclosure	PO DIFF 	0.08 )
( minEnclosure	DIFF CO 	0.01 )
( minEnclosure	M1 CO 	0.004 )
( endOfLineEnclosure	M1 VIA1 	0.005 )
( endOfLineEnclosure	M2 VIA1 	0.005 )
( endOfLineEnclosure	M2 VIA2 	0.005 )
( endOfLineEnclosure	M3 VIA2 	0.005 )
( endOfLineEnclosure	M3 VIA3 	0.005 )
( endOfLineEnclosure	M4 VIA3 	0.005 )
( endOfLineEnclosure	M4 VIA4 	0.005 )
( endOfLineEnclosure	M5 VIA4 	0.005 )
( endOfLineEnclosure	M5 VIA5 	0.005 )
( endOfLineEnclosure	M6 VIA5 	0.005 )
( endOfLineEnclosure	M6 VIA6 	0.005 )
( endOfLineEnclosure	M7 VIA6 	0.005 )
( endOfLineEnclosure	M7 VIA7 	0.005 )
( endOfLineEnclosure	M8 VIA7 	0.005 )
( endOfLineEnclosure	M8 VIA8 	0.03 )
( endOfLineEnclosure	M9 VIA8 	0.03 )
( endOfLineEnclosure	DIFF CO 	0.01 )
( endOfLineEnclosure	M1 CO 	0.035 )
( defWidth	CO 	0.042 )
( defWidth	DIFF 	0.12 )
( defWidth	DIFF_18 	0.33 )
( defWidth	DM1EXCL 	0.45 )
( defWidth	DM2EXCL 	0.45 )
( defWidth	DM3EXCL 	0.45 )
( defWidth	DM4EXCL 	0.45 )
( defWidth	DM5EXCL 	0.45 )
( defWidth	DM6EXCL 	0.45 )
( defWidth	DM7EXCL 	0.45 )
( defWidth	DM8EXCL 	0.45 )
( defWidth	DM9EXCL 	0.45 )
( defWidth	DNW 	3 )
( defWidth	HVTIMP 	0.85 )
( defWidth	IP 	0.1 )
( defWidth	LOGO 	0.45 )
( defWidth	LVTIMP 	0.85 )
( defWidth	M1 	0.05 )
( defWidth	M2 	0.056 )
( defWidth	M3 	0.056 )
( defWidth	M4 	0.056 )
( defWidth	M5 	0.056 )
( defWidth	M6 	0.056 )
( defWidth	M7 	0.056 )
( defWidth	M8 	0.056 )
( defWidth	M9 	0.16 )
( defWidth	MRDL 	2 )
( defWidth	NIMP 	0.17 )
( defWidth	NWELL 	0.65 )
( defWidth	PAD 	30 )
( defWidth	PIMP 	0.17 )
( defWidth	PO 	0.03 )
( defWidth	SBLK 	0.33 )
( defWidth	VIA1 	0.05 )
( defWidth	VIA2 	0.05 )
( defWidth	VIA3 	0.05 )
( defWidth	VIA4 	0.05 )
( defWidth	VIA5 	0.05 )
( defWidth	VIA6 	0.05 )
( defWidth	VIA7 	0.05 )
( defWidth	VIA8 	0.13 )
( defWidth	VIARDL 	2 )
( defWidth	PrBoundary 	0.45 )
( validRoutingLayers	( CO DIFF DIFF_18 M1 M2 M3 M4 M5 M6 M7 M8 M9 MRDL PO VIA1 VIA2 VIA3 VIA4 VIA5 VIA6 VIA7 VIA8 VIARDL ) )
 );foundry
( LEFDefaultRouteSpec  
( minWidth	CO 	0.042 )
( horizontalRouteGridPitch	M1 	0.2 )
( verticalRouteGridPitch	M1 	0.2 )
( horizontalRouteGridOffset	M1 	0.1 )
( verticalRouteGridOffset	M1 	0.1 )
( minWidth	M1 	0.05 )
( minWireExtension	M1 	0.105 )
( minWidth	VIA1 	0.05 )
( horizontalRouteGridPitch	M2 	0.3 )
( verticalRouteGridPitch	M2 	0.3 )
( horizontalRouteGridOffset	M2 	0.15 )
( verticalRouteGridOffset	M2 	0.15 )
( minWidth	M2 	0.056 )
( minWireExtension	M2 	0.105 )
( minWidth	VIA2 	0.05 )
( horizontalRouteGridPitch	M3 	0.3 )
( verticalRouteGridPitch	M3 	0.3 )
( horizontalRouteGridOffset	M3 	0.15 )
( verticalRouteGridOffset	M3 	0.15 )
( minWidth	M3 	0.056 )
( minWireExtension	M3 	0.105 )
( minWidth	VIA3 	0.05 )
( horizontalRouteGridPitch	M4 	0.3 )
( verticalRouteGridPitch	M4 	0.3 )
( horizontalRouteGridOffset	M4 	0.15 )
( verticalRouteGridOffset	M4 	0.15 )
( minWidth	M4 	0.056 )
( minWireExtension	M4 	0.105 )
( validRoutingLayers	( M1 M2 M3 M4 ) )
( validRoutingVias	( VIA12 VIA12BAR VIA12LG VIA12C VIA12BARC VIA12LGC VIA23 VIA23BAR VIA23LG VIA23C VIA23BARC VIA23LGC VIA34 VIA34BAR VIA34LG VIA34C VIA34BARC VIA34LGC POLYCON1 POLYCON1C POLYCON2 POLYCON2C DIFFCON VIA45 VIA45BAR VIA45LG VIA56 VIA56BAR VIA56LG VIA67 VIA67BAR VIA67LG VIA78 VIA78BAR VIA78LG VIA89 ) )
 );LEFDefaultRouteSpec
) ;constraintGroups

